import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { Changa, Tajawal, Montserrat } from "next/font/google";

const changa = Changa({ weight: "700" }); // Bold for Arabic
const tajwal = Tajawal({ weight: "300" }); // Light for both Arabic & English
const montserrat = Montserrat({ weight: "700" }); // Bold for English

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{ children: React.ReactNode }>) {
  const awaitedParams = await params;
  const locale = awaitedParams.locale;

  const isArabic = locale === "ar";
  const direction = isArabic ? "rtl" : "ltr";

  const fontClass = isArabic ? changa.className : montserrat.className;

  return (
    <html lang={locale} dir={direction}>
      <body className={`font-tajawal ${tajwal.className} ${fontClass}`}>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
